# This workflow will build a docker container, publish it to Azure Container Registry, and deploy it to Azure Kubernetes Service using a helm chart.
#
# https://github.com/Azure/actions-workflow-samples/tree/master/Kubernetes
#
# To configure this workflow:
#
# 1. Set up the following secrets in your workspace:
#     a. REGISTRY_USERNAME with ACR username
#     b. REGISTRY_PASSWORD with ACR Password
#     c. AZURE_CREDENTIALS with the output of `az ad sp create-for-rbac --sdk-auth`
#
# 2. Change the values for the REGISTRY_NAME, CLUSTER_NAME, CLUSTER_RESOURCE_GROUP and NAMESPACE environment variables (below).
name: test scanning
on:
  push:
    branches:
      - test-scanning

# Environment variables available to all jobs and steps in this workflow
env:
  REGISTRY_NAME: k8scc01covidacr
  REGISTRY: k8scc01covidacr.azurecr.io
  CLUSTER_NAME: k8s-cancentral-01-covid-aks
  CLUSTER_RESOURCE_GROUP: k8s-cancentral-01-covid-aks
  LATEST_IMAGE_TAG: master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    # Connect to Azure Container registry (ACR)
    - uses: azure/docker-login@v1
      with:
        login-server: ${{ env.REGISTRY_NAME }}.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    # - name: Free disk space
    #   run: |
    #     df -h
    #     sudo swapoff -a
    #     sudo rm -f /swapfile
    #     sudo apt clean
    #     docker rmi $(docker image ls -aq)
    #     df -h

    # DEBUG: FAKE BUILD
    # Container build and push to a Azure Container registry (ACR)
    # DEBUG: NOTE THIS DOES NOT PUSH - MUST SCAN LOCALLY!
    - name: Base Notebook CPU (fake)
      id: base-notebook-cpu
      working-directory: ./base-notebook/
      env:
        IMAGE_NAME: base-notebook-cpu-fake
      run: |
        # Get upstream image from build_settings.env

        (source ../build_settings.env && \
         ../scripts/build_push.sh --registry ${{ env.REGISTRY }} \
                                            --image_name ${{ env.IMAGE_NAME }} \
                                            --tag_pinned ${{ github.sha }} \
                                            --tag_latest ${{ env.LATEST_IMAGE_TAG }} \
                                            --cache_from ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.LATEST_IMAGE_TAG }} \
                                            --base_container $UPSTREAM_CONTAINER_CPU \
        )

    # # Scan image for vulnerabilities (image that should work)
    # - uses: Azure/container-scan@v0
    #   with:
    #     image-name: k8scc01covidacr.azurecr.io/base-notebook-cpu:379b54eaae9bf55e83c4da0855060ae170ef7c0f
    #     severity-threshold: CRITICAL
    #     run-quality-checks: false

    # Scan image for vulnerabilities (new image)
    - uses: Azure/container-scan@v0
      env:
        TRIVY_TIMEOUT: 0m5s
      with:
        image-name: ${{ steps.base-notebook-cpu.outputs.tag_pinned }}
        # image-name: k8scc01covidacr.azurecr.io/base-notebook-cpu:379b54eaae9bf55e83c4da0855060ae170ef7c0f
        severity-threshold: CRITICAL
        run-quality-checks: false
